creation_rules:
  - path_regex: hosts/macbook-pro
    key_groups:
      - age:
          - age1e06gkr9e24cstp8kdvccdal0ekkeqtcl4ltvak0fqcsqa2dayp3svtjwcq # root@macbook-pro
          - age1kvq49jdepnwtl4duwep6t6lhzdk59c4ljnmla3025q34jcx98uys0k78qx # michaelvanstraten@macbook-pro
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - age1kvq49jdepnwtl4duwep6t6lhzdk59c4ljnmla3025q34jcx98uys0k78qx # michaelvanstraten@macbook-pro
          - age16gue9smyyte76y085zj38ax7a6rwm0yrmue6m3q0k8y8duknc5rqp4cj9v # root@dxp4800plus
