keys:
  # Master Keys
  - &ssh_michael_macbook_pro "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8OCYTaHjQy7Y7bRmxzVwNBgnD9P21UQPzVpJ3NKwVV"
  - &yubikey "4B92 DBDE 172E 7C69 16F0  04EE 8560 19C4 9BE6 D7C0"
  # Host Keys
  - &host_macbook_pro "age15qzjd9u3mqyqgsyyq7fy6dr0mkkc82rtvdpevfvvtv6j56z2k9vscqhmfs"
  - &host_mac_studio "age1l0vmpvuchm7cvesu0mpwltc6fe830j8jh5j7m0l2gw4gj0shze8q3uylj5"
  # User SSH Keys
  - &ssh_michael_mac-studio "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7atwi/0OoP5kHlgIbWRMctz5zT1s9WGQEkQ3wHMdbC"

creation_rules:
  - path_regex: ^hosts/macbook-pro/.*$
    pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro, *host_macbook_pro]

  - path_regex: ^hosts/mac-studio/secrets\.yaml$
    pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro, *host_mac_studio, *ssh_michael_mac-studio]

  - pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro]
