keys:
  # Master Keys
  - &ssh_michael_macbook_pro "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8OCYTaHjQy7Y7bRmxzVwNBgnD9P21UQPzVpJ3NKwVV"
  - &yubikey "4B92 DBDE 172E 7C69 16F0  04EE 8560 19C4 9BE6 D7C0"
  # Host Keys
  - &host_macbook_pro "age15qzjd9u3mqyqgsyyq7fy6dr0mkkc82rtvdpevfvvtv6j56z2k9vscqhmfs"
  - &host_mac_studio "age1l0vmpvuchm7cvesu0mpwltc6fe830j8jh5j7m0l2gw4gj0shze8q3uylj5"
  - &host_netcup_vps_1000_arm_1 "age12cm60732er6qha4k42e2xa0vtl8n55rnf0qey0gac4n6d6kg9cdqenjjl2"
  - &host_dxp4800plus "age196wp4u9e954sktpx37dpr8yadm33gfd4h27np8stcs3j8w8jnuyszsl06j"
  # User SSH Keys
  - &ssh_michael_mac-studio "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7atwi/0OoP5kHlgIbWRMctz5zT1s9WGQEkQ3wHMdbC"

creation_rules:
  - path_regex: ^hosts/macbook-pro/.*$
    pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro, *host_macbook_pro]

  - path_regex: ^hosts/mac-studio/secrets\.yaml$
    pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro, *host_mac_studio, *ssh_michael_mac-studio]

  - path_regex: ^hosts/netcup-vps-1000-arm-1/.*$
    pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro, *host_netcup_vps_1000_arm_1]

  - path_regex: ^hosts/dxp4800plus/.*$
    pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro, *host_dxp4800plus]

  - pgp: [*yubikey]
    age: [*ssh_michael_macbook_pro]
